### ISSUE TITLE
problem running test_main.py with pytest

### ISSUE THREAD

**Issue by mjaddis** [JiscRDSS/rdss-par#17]
I'm trying to run test_main.py on the command line using pytest, e.g. $ pytest testing/test_main.py

It bombs out because a '.' at the start of 'const' in the library import line at the top.  Removing the . fixes this.

It then moans it can't find the files in the 'schema' and 'examples' directory.   They appear to need to be subdirectories of the testing directory.  Maybe this is a problem with how os.path.join works in const.py.  

If I copy the schema and example directories into the testing directory then it works fine.  

Am I doing something wrong or does test_main.py need fixing?

**Comment by sevein** [comment]
@mjaddis I couldn't reproduce the error that you're describing.

To make sure that we're using a similar environment I've tried to reproduce using Docker:

$ docker run -it python:3.6 bash
$ git clone https://github.com/JiscRDSS/rdss-par
$ cd rdss-par
$ pip install -r requirements.txt
$ pip install pytest
$ pytest -v

```
root@32f48472c85d:/rdss-par# pytest -v
============================ test session starts =============================
platform linux -- Python 3.6.6, pytest-3.6.2, py-1.5.4, pluggy-0.6.0 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /rdss-par, inifile:
collected 4 items

testing/test_main.py::FormatTest::runTest PASSED                                           [ 25%]
testing/test_main.py::PreservationActionTest::runTest PASSED                               [ 50%]
testing/test_main.py::ToolTest::runTest PASSED                                             [ 75%]
testing/test_main.py::PropertyTest::runTest PASSED                                         [100%]

========================== 4 passed in 0.06 seconds ==========================
```

**Comment by mjaddis** [comment]
Thanks Jesus, that works for me.  Maybe the problems I had were because I was running python2.7 rather than 3.6.   Anyway, works now - thanks for the help.

**Comment by mjaddis** [comment]
I used virtualenv to install/run pytest with python3.   test_main.py works fine so this definitely looks to be a python2 v python3 issue.   I'm going to close this issue on the basis that test_main.py does infact work fine.
